// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3IPGaw3AaOKC-HsfgV2_oFPdr-M4f6HI',
    appId: '1:498011456712:android:056c336774626f36df91fd',
    messagingSenderId: '498011456712',
    projectId: 'selivery-395216',
    databaseURL: 'https://selivery-395216-default-rtdb.firebaseio.com',
    storageBucket: 'selivery-395216.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKsZxlJkhxkPZIwIW69zysBx9YF92Ric0',
    appId: '1:498011456712:ios:a381b047f60c7efddf91fd',
    messagingSenderId: '498011456712',
    projectId: 'selivery-395216',
    databaseURL: 'https://selivery-395216-default-rtdb.firebaseio.com',
    storageBucket: 'selivery-395216.appspot.com',
    androidClientId: '498011456712-37lfqprlrqnee9us551d7flli000u30h.apps.googleusercontent.com',
    iosClientId: '498011456712-tvns1mmshm1mi5v2c9pb636vknckjsdk.apps.googleusercontent.com',
    iosBundleId: 'com.example.seliveryDriver',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDltraag7HPas7f3NvQvDFuGLCwsciXuhg',
    appId: '1:498011456712:web:94e0a812bb9212c3df91fd',
    messagingSenderId: '498011456712',
    projectId: 'selivery-395216',
    authDomain: 'selivery-395216.firebaseapp.com',
    databaseURL: 'https://selivery-395216-default-rtdb.firebaseio.com',
    storageBucket: 'selivery-395216.appspot.com',
    measurementId: 'G-RT0117YYPL',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKsZxlJkhxkPZIwIW69zysBx9YF92Ric0',
    appId: '1:498011456712:ios:a381b047f60c7efddf91fd',
    messagingSenderId: '498011456712',
    projectId: 'selivery-395216',
    databaseURL: 'https://selivery-395216-default-rtdb.firebaseio.com',
    storageBucket: 'selivery-395216.appspot.com',
    androidClientId: '498011456712-37lfqprlrqnee9us551d7flli000u30h.apps.googleusercontent.com',
    iosClientId: '498011456712-tvns1mmshm1mi5v2c9pb636vknckjsdk.apps.googleusercontent.com',
    iosBundleId: 'com.example.seliveryDriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDltraag7HPas7f3NvQvDFuGLCwsciXuhg',
    appId: '1:498011456712:web:3b5cd93cb568c4dcdf91fd',
    messagingSenderId: '498011456712',
    projectId: 'selivery-395216',
    authDomain: 'selivery-395216.firebaseapp.com',
    databaseURL: 'https://selivery-395216-default-rtdb.firebaseio.com',
    storageBucket: 'selivery-395216.appspot.com',
    measurementId: 'G-NVB2BLB2E9',
  );

}